### ISSUE TITLE
Large package-lock.json

### ISSUE THREAD

**Issue by fkirc** [actions/typescript-action#138]
Please correct me if I am wrong:
Whenever an action runs for the first time in a specific workflow, the action-runner fetches an entire shallow-commit on the fly.

This raises the question about repo-size.
Currently, package-lock.json is 346 KB.
This would not be a big deal, but the action-runner might download it all the time.
Are there any suggestions on how to reduce this overhead?

**Comment by hross** [comment]
It is not ideal but you are right that it will get downloaded every time. Unfortunately I don't have any suggestions to fix this at the moment.

**Comment by crazy-max** [comment]
@hross I use yarn for [all my actions](https://github.com/crazy-max?utf8=%E2%9C%93&tab=repositories&q=github-actions&type=source&language=) and it cuts the size by half approx. ~150KB
This also allows to remove extra fields like _args and where which contain the absolute path of modules which could conflicts when merged. I can open a PR if you are interested.
See https://github.com/docker/setup-buildx-action/blob/master/package.json as an example.

**Comment by hross** [comment]
I like the idea but we have a lot of other actions using this mechanism right now so I don't want to change that for the core template.
