### ISSUE TITLE
Improve Onboarding Experience

### ISSUE THREAD

**Issue by aolszowka** [actions/typescript-action#150]
First thank you for this template, this looks like a good way to quickly bootstrap into GitHub Actions.

However, I feel the on boarding experience could be improved. After cloning this repository you get at least 8 issues immediately opened up by Dependabot.

While it is super helpful to have automated dependency checking (especially in a dependency tree as deep as this), this feels like a negative user experience. I would agree with maybe having one or two (at most) out of date dependencies to give users a feel for how this process should work, but flooding a new clone is a bit steep.

Furthermore as far as I can see this process is not documented anywhere in the README. While it should be expected that if you're writing an action you know what you're doing, but it can be a jolt even when you realize what is occurring.

**Comment by hross** [comment]
we try to keep this up to date but of course the dependencies move so sometimes you will get these PRs. Apologies and we will try to keep the repo up to date.
