### ISSUE TITLE
Lock "@types/node" to the version that runner uses

### ISSUE THREAD

**Issue by Cyberbeni** [actions/typescript-action#187]
I had an issue of os.version being undefined then I realized that it was introduced in Node.js 12.17 and GitHub runner is using an earlier version of Node.js to run action. I beleive this would solve the issue of accidentally using types that are not available during run.

This should preferably be done in a way, that stuff like `yarn upgrade --latest` don't update this to the latest one.

**Comment by Wampy2** [comment]
Djjdjdz

**Comment by ncalteen** [comment]
👋🏻 Hello! Apologies for the delay on this issue. I am going through this repository and making some large updates. This will be resolved by #732
