### ISSUE TITLE
actions.yml are required in master and branch

### ISSUE THREAD

**Issue by JJ** [actions/typescript-action#20]
However, there does not seem to be a big problem if they are different. I have changed `action.yml` in master and not updated it in `releases/v1`, and there didn't seem to be any major problem. Could it be that the metadata in one and the other can be different? Or maybe that it's just not needed in `master` and is there just for the show?

**Comment by damccorm** [comment]
Its needed in master if you're going to reference `uses: action@master`, but it isn't needed otherwise. Its still probably best practice to have it though since that's going to be where people first land in your repo and the `action.yml` defines the metadata for their action

**Comment by JJ** [comment]
Which takes me back to #18. It would be very helpful to know exactly what files are needed in every place.
I see now that the main way of using this would be to work and test in `master` and then create a release only when there's absolute conviction everything is working... It would be helpful if that was clarified in the documentation... somewhere. (From the get go, it wasn't too clear to me that you could actually test an action in master)

**Comment by bryanmacfarlane** [comment]
Closing since Danny answered above.
