### ISSUE TITLE
Comment should be changed to ACTIONS_STEP_DEBUG

### ISSUE THREAD

**Issue by tonyhallett** [actions/typescript-action#240]
https://github.com/actions/typescript-action/blob/b4f07da86601110b682c6f45ff575f5fbd0f8cdf/src/main.ts#L7

The secret ACTIONS_RUNNER_DEBUG does not work.  ACTIONS_STEP_DEBUG does

**Comment by ncalteen** [comment]
Hello! Thank you for pointing this out, and apologies for the delay in responding to your issue. This has been updated in the repository.
