### ISSUE TITLE
Documentation on testing with jest is flawed

### ISSUE THREAD

**Issue by jacobcrawford** [actions/typescript-action#243]
The documentation is not specifying how one can extend the tests to a typescript based action.

How do you specify input for the action in a test setup?

**Comment by oirodolfo** [comment]
Isn't it by passing an environment variable?

**Comment by jacobcrawford** [comment]
Maybe. The README does not state how to extend the jest tests, only how to run them in the first place. 
For changing the action functionality, the toolkit documentation is referenced, but for the local tests, no comments are made.
If the template holds initial test, it should also say how to expand these and how they communicate with the action code.

**Comment by markgoho** [comment]
added a PR that should clear up this issue #455

**Comment by ncalteen** [comment]
Hi All,

Apologies for the delay on responding to this issue. I am working through a number of cleanup tasks on this repository. I've adjusted the tests that are included in the template to be a bit more descriptive and (hopefully) easier to follow. Please take a look at #732 and add any comments/feedback there!
