### ISSUE TITLE
Husky hooks?

### ISSUE THREAD

**Issue by ibrasho** [actions/typescript-action#25]
The [contributers](https://github.com/actions/typescript-action/blob/master/docs/contributors.md) file mentions Husky hooks but they are not defined in `package.json`.

Can they be added to the repo?

**Comment by bryanmacfarlane** [comment]
We moved away from Husky.  We will fix that file.

**Comment by bryanmacfarlane** [comment]
Fixed with https://github.com/actions/typescript-action/commit/7de0c72a57d210cd49713faebaab1db2d0f78fba

Stale doc which was replaced with the walk through.

Thanks for pointing this out!
