### ISSUE TITLE
types for the payload?

### ISSUE THREAD

**Issue by retorquere** [actions/typescript-action#254]
I'm trying to cast the payload to the correct type, but I haven't been able to find the typings -- looks like they ought to come from `@octokit/webhooks`, but I've had no luck. Trying to do something like

```
const payload = github.context.payload as Webhooks.WebhooksEvents.WebhookPayloadIssues
```

but that gets me a compilation error.

**Comment by tonyhallett** [comment]
`import {EventPayloadMap} from '@octokit/webhooks-definitions/schema'`

and key into the map - e.g 
```
github.context.payload as EventPayloadMap['issues']
```

**Comment by olly** [comment]
The types for the Events can be used like so:

```typescript
import { PushEvent, PullRequestEvent } from '@octokit/webhooks-definitions/schema'

const payload = github.context.payload as PullRequestEvent
```

**Comment by retorquere** [comment]
Thanks! Got it working.
