### ISSUE TITLE
Build automation in Dependabot / fork contexts

### ISSUE THREAD

**Issue by namoscato** [actions/typescript-action#281]
I've had some success auto-building / committing the compiled [`ncc`](https://github.com/vercel/ncc) package in PR contexts (i.e. via [git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action)) but am running into challenges with Dependabot updates now that those workflows [run with read-only permissions](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/).

I realize this issue is only tangentially related to this template (given it uses `ncc`), but do you have any process recommendations to ensure the committed package is kept up to date in these contexts?

I've read [this blog](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) several times but haven't had much success with the recommendations – some of which seem complicated.

**Comment by myyk** [comment]
This commit has changes which shows how you can auto-build / commit the compiled `ncc` package with further comments on how to auto-merge it. https://github.com/actions/typescript-action/pull/327

**Comment by ncalteen** [comment]
Taking some time to review, I'm not sure this is something we would want to implement in the template repository. Using the `pull_request_target` event type introduces a number of [security risks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) and the potential for misconfigurations is pretty high.
