### ISSUE TITLE
Add webpack config example

### ISSUE THREAD

**Issue by eine** [actions/typescript-action#30]
The README suggests a not easy process to update release branches which keeps unnecessary files. Using packagers, such as webpack, allows to distribute actions as a single js file. The following example has been successfully tested with actions based on this template:

```js
const join = require('path').join;

module.exports = {
  entry: './src/main.ts',
  target: 'node',
  output: {
    path: join(__dirname, 'dist'),
    filename: 'main.js',
  },
  devtool: 'source-map',
  resolve: { extensions: ['.ts', '.js'] },
  module: {
    rules: [{
      test: /\.ts$/,
      exclude: /node_modules/,
      use: [{
        loader: 'ts-loader',
      }]
    }]
  },
};
```

See, for example:

- master: https://github.com/1138-4EB/issue-runner/tree/master
- release branch: https://github.com/1138-4EB/issue-runner/tree/gha-tip

It'd be good if:

- Instructions about how to use one or multiple packagers are added to the README or some other md file.
- The default/suggested procedure was to use a packager.

**Comment by bryanmacfarlane** [comment]
This was fixed by moving to ncc pack in packages.json script and then releasing in dist folder.  Thanks for the suggestion!
