### ISSUE TITLE
block should have a `-` for the section

### ISSUE THREAD

**Issue by jsoref** [actions/typescript-action#306]
https://github.com/actions/typescript-action/blob/b4f07da86601110b682c6f45ff575f5fbd0f8cdf/README.md#L96-L98

Compare:
https://github.com/actions/checkout/blob/25a956c84d5dd820d28caab9f86b8d183aeeff3d/README.md?plain=1#L37-L38

**Comment by ncalteen** [comment]
👋🏻 Hello! Apologies for the delay on this issue. I am going through this repository and making some large updates. This will be resolved by #732

**Comment by jsoref** [comment]
It's fine. I'm happy not to leave a PR open for 2 years.

**Comment by ncalteen** [comment]
Understood and sorry again!
