### ISSUE TITLE
action.yml runs main dist/index.js but dist isn't generated by scripts

### ISSUE THREAD

**Issue by South-Paw** [actions/typescript-action#44]
Just been using this as an example to set up a [new action](https://github.com/South-Paw/action-report-coverage) and I noticed that `action.yml` contains the following:

```yaml
runs:
  using: 'node12'
  main: 'dist/index.js'
```

but it doesn't seem that `dist` is generated by any of the scripts and other files (such as the run test) reference the generated `lib` folder as the runner

Since there isn't a mention of the `dist` folders purpose in the readme, am I misunderstanding how this is utilized or is this an oversight? 🤔

**Comment by South-Paw** [comment]
Realized now that `ncc` generates `dist` while `tsc` generates `lib` which the test runs.

**Comment by Gowee** [comment]
As a newbie to the TS ecosystem, I find it farily confusing.

After tons of trys, finally, I realize that the proper workflow to build is `yarn build && yarn package` where the former produces `lib/*` and the latter generates `dist/*` from `lib/*`.
