### ISSUE TITLE
Document the intended usage workflow

### ISSUE THREAD

**Issue by chancancode** [actions/typescript-action#45]
Hi! I didn't know about the "template" feature on GitHub and it took me some time (and help from a friend) to figure out the "correct" way to use this repository. Initially, I had cloned from the Git CLI and hand-tweaked the files, but I later found out that there is the "Use this template" button I am supposed to use instead.

Maybe this is on the a different team to make that UI a little more discoverable in general, but it probably wouldn't hurt to mention this in the first sentence of the readme, either explicitly ('Click the "Use this template" button above to get started.') or turn the word "template" into a link to the appropriate GitHub documentation (not sure where that page is though).

**Comment by bryanmacfarlane** [comment]
Thanks for the issue.  It's now here in the readme: https://github.com/actions/typescript-action#create-an-action-from-this-template
