### ISSUE TITLE
Prettier parser choice (TypeScript) makes it harder and confusing to format YAML files

### ISSUE THREAD

**Issue by ivanosevitch** [actions/typescript-action#47]
## Steps to reproduce

- Clone this repo
- Run inside it `npm i`
- Open the repo with VS Code, in which:
  - Prettier VS Code extension is installed: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
  - `"editor.formatOnSave": true` in VS Code Settings (or use the `Format Document` VS Code command when editing the below file)
- _note: the same could be done with IntelliJ IDEs_
- Edit `action.yml`, save the file

### Expected

The file is formatted as a YAML file by Prettier.

### Actual behavior

The file is formatted as a TypeScript file by Prettier, messing up its formatting:

```
name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
runs: using: 'node12' # messed up formatting
main: 'dist/index.js'
```

## Fix

Prettier is perfectly capable of selecting the needed parser on its own.
From [Prettier config documentation](https://prettier.io/docs/en/configuration.html#setting-the-parserdocsenoptionshtmlparser-option):

> Never put the parser option at the top level of your configuration. Only use it inside overrides. Otherwise you effectively disable Prettier's automatic file extension based parser inference. This forces Prettier to use the parser you specified for all types of files – even when it doesn't make sense, such as trying to parse a CSS file as JavaScript.

As such the recommended fix would be to remove the Prettier `parser` configuration.
When removed, Prettier will select the TypeScript parser to format the TypeScript files of this repo.

I've opened a PR to do just that 😀 : https://github.com/actions/typescript-action/pull/48

**Comment by bryanmacfarlane** [comment]
Thanks for filing such a detailed issue explaining the problem.   I'm open to the change but I was wondering if a better fix isn't to add the action yaml (and .github folder with yaml) to the prettier ignore file?

**Comment by ivanosevitch** [comment]
Hi Bryan!

Adding for example `*.yml` in `.prettierignore` would indeed solve the issue.

I'd however argue to let Prettier format YAML files, because:
- Prettier has indeed been able to format YAML files, in a fully YAML spec-compliant way, for about 2 years now
- In my teaching of YAML-based CI/CD config (mainly CircleCI and GitHub Actions) to other people, about half of the errors were coming from malformed YAML
  - The indentation-based syntax of YAML can indeed be [hard to read](https://www.arp242.net/yaml-config.html#can-be-hard-to-edit-especially-for-large-files). A formatter (like Prettier) can help to declutter the visual space, and an malformed config would make Prettier throw an error.

---
However, Prettier is opinionated and you may not adhere to its style guidelines (for example, single quotes versus double quotes).

Additionally, a better (and complementary) tool would be a proper linter (like `yamllint`).
Another tool could be an Actions-aware config validator (like CircleCI does with their command line `circleci config validate`), to let developers know of an invalid config before it's pushed to GitHub, and let them iterate faster.

---
I've taken the liberty to format the action and workflow YAML files in my PR, which has the advantage of aligning their style (one was using single quote, the other double quote; sometimes list elements were indented, sometimes they weren't).

Note: my PR won't conflict with the upgrade to Prettier v2: https://github.com/actions/typescript-action/pull/56. They order in which they (if deemed ok) would be merged does not matter.
