### ISSUE TITLE
"Publish to a distribution branch" instructions need to be updated 

### ISSUE THREAD

**Issue by hashtagchris** [actions/typescript-action#49]
As of https://github.com/actions/typescript-action/pull/42, it looks like you use ncc to release version of your action. I think the following should be done:

- [x] `dist` should be added to `.gitignore`, to prevent usage of actions from the master branch. See https://aka.ms/nomasters and https://github.com/actions/starter-workflows/pull/240

- [x] Everything about `node_modules` should be removed from the "Publish to a distribution branch" instructions in README.md. It's not necessary to commit `node_modules` any more.

- [ ] The "Publish to a distribution branch" instructions should tell you to run `npm run pack` and to comment out `dist` from `.gitignore`.  Better yet, `git add -f dist/index.js` could be used in the distribution branch. Maybe `git add --force dist/index.js` could be added as another npm script.

**Comment by hross** [comment]
I'm not sure I agree we should be adding dist to ignore. I don't like the usage of master, but I also don't like making complicated release steps. I will make the change to the readme to reflect the usage of ncc.

**Comment by joshmgross** [comment]
Adding `dist` to `.gitignore` is a good way to prevent actions authors from accidentally pushing release dependencies to `master`. If they unknowingly do it, it would mean that:
1. `master` is usable by users
2. `master` is potentially outdated if the author isn't consistently updating those dependencies

To avoid a complicated release step, just combine `ncc` with `gid add` in the same `npm` script. 

It could be `"pack": "ncc build src/main.js && git add -f dist/"`

**Comment by samuelmeuli** [comment]
I also think `dist` should be ignored on `master`. In addition to the reasons mentioned above, action authors may receive pull requests which introduce or change dependencies. If `dist` is part of the PR and the code isn't inspected carefully, this might be a security issue.

> I don't like the usage of master, but I also don't like making complicated release steps

The process could be delegated to a new action 😉 The action could run `pack` after each push and automatically commit `dist` to the `release` branch. This would simplify the release process – all authors would need to do is tag the commit they want to release.
