### ISSUE TITLE
npm install is failing due to eslint

### ISSUE THREAD

**Issue by anilkreddy** [actions/typescript-action#587]
After cloning this repository or using this as template to create new repository `npm install` is failing with these errors

<img width="824" alt="image" src="https://user-images.githubusercontent.com/5541121/187058665-1e351ea2-ded0-4590-8525-f9b19eae6022.png">

**Comment by Yuri6037** [comment]
I tried initializing a repository with this template and got the exact same problem. Gonna have to get rid of eslint!
