### ISSUE TITLE
Add typing + validation workflow

### ISSUE THREAD

**Issue by krzema12** [actions/typescript-action#591]
I'm the author of https://github.com/krzema12/github-actions-typing/ which aims at bringing more type-safety in the world of GitHub Actions' APIs. There's already one library that makes active use of it: https://github.com/krzema12/github-actions-kotlin-dsl.

To increase adoption of this approach, I propose considering including support for it in this template repository, that is:
* adding an `action-types.yml` file
* adding a workflow that would use an action in [the mentioned repository](https://github.com/krzema12/github-actions-typing/) to validate the file mentioned above

Example of how it was integrated with an existing action: https://github.com/ReactiveCircus/android-emulator-runner/commit/a410b40679583e6c48709e28b6aae2c9e335b90e

If you're open to introducing it, I'll be happy to create a PR. If you have any feedback that would need to be addressed prior to introducing it to the wider audience, I'll be happy to address it.

**Comment by ncalteen** [comment]
Hi @krzema12! Apologies for the delay in responding to this issue! I'd be interested in taking a look at how this functions. Please feel free to submit a PR and we will check it out 😄  In the meantime, I will close out this issue unless there is anything else I can help you with.

**Comment by krzema12** [comment]
Thanks @ncalteen, here's a PR, please review: #744.
