### ISSUE TITLE
bootgrubgrub.cfg

### ISSUE THREAD

**Issue by Israelromero117** [actions/typescript-action#596]
bootgrubgrub.cfg

_Originally posted by @israelromero19 in https://github.com/actions/upload-artifact/issues/332#issuecomment-1236439268_

**Comment by ncalteen** [comment]
Hello! Apologies for the delay on replying to this issue. I am working on cleaning up this repository and making necessary updates based on developer feedback. If there is an existing need or action to take on this issue, please reopen and comment with any additional information/context that will help us assist!
