### ISSUE TITLE
Turn on Dependabot security updates

### ISSUE THREAD

**Issue by clarkbw** [actions/typescript-action#60]
When recently using this template there were several security issues that needed to be updated.  I was wondering if we could turn on auto-security PRs for this repo so users don't create a new repo from the template and need to immediately update the dependent versions.

Thanks!

**Comment by mforutan** [comment]
Looks like this has been enabled: #55, but still there are two other issues that Dependabot is not able to fix:
![image](https://user-images.githubusercontent.com/13926799/81631068-674fdf80-944a-11ea-8946-adefa1a15f08.png)

**Comment by clarkbw** [comment]
Hmm, I guess we need to merge the existing ones and likely do a manual update as well.

**Comment by hross** [comment]
working on this now....
