### ISSUE TITLE
draft-ietf-httpbis-p3-payload-14

### ISSUE THREAD

**Issue by Israelromero117** [actions/typescript-action#600]
https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-p3-payload-14#section-3.2

**Comment by ncalteen** [comment]
Hello! Apologies for the delay on replying to this issue. I am working on cleaning up this repository and making necessary updates based on developer feedback. If there is an existing need or action to take on this issue, please reopen and comment with any additional information/context that will help us assist!
