### ISSUE TITLE
eslint-plugin-prettier missing from devDependencies?

### ISSUE THREAD

**Issue by chancancode** [actions/typescript-action#61]
When running the `all` script after cloning, the eslint step failed with the following error:

```

Oops! Something went wrong! :(

ESLint: 5.16.0.
ESLint couldn't find the plugin "eslint-plugin-prettier". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-prettier is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-prettier@latest --save-dev

Path to ESLint package: .../node_modules/eslint

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

```

Didn't dig into what was causing the plugin to be needed, but adding `eslint-plugin-prettier` to `devDependencies` fixes the issue.

**Comment by hross** [comment]
you need to run `npm install` before you run `npm run all`.

We have a [passing test here](https://github.com/actions/typescript-action/runs/889600138?check_suite_focus=true) that simulates checkout on a clean machine and running `npm install` before running `npm run all` that appears to work so I think I can close this.

Refer to the scripts in that tests if you want to see the sequence. Let me know if you have a repro scenario and we can re-open this.
