### ISSUE TITLE
.eslintrc.json is badly formatted

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [actions/typescript-action#616]
As per the title, the `.eslintrc.json` is wrongly indented for all lines except the first opening brace. This is a bit nitpicky but something that can be fixed nonetheless. I can quickly create a PR if accepted.

**Comment by ncalteen** [comment]
👋🏻 Hello! Apologies for the delay on this issue. I am going through this repository and making some large updates. This will be resolved by #732 (specifically, `.eslintrc.json` is being moved to `.github/linters/.eslintrc.yml` and the corresponding `npm lint` script in `package.json` is being updated accordingly)
