### ISSUE TITLE
Keep dependencies up to date

### ISSUE THREAD

**Issue by andreasabel** [actions/typescript-action#623]
Hi, I instantiated this template to create an action, and immediately got PRs from dependabot to bump outdated actions.
It would probably be good to keep this template up to date so that one does not get these alerts downstream already at the time of forking...

At the time of writing, there is half a dozen dependabot PRs open, with the oldest from April 2022:
- https://github.com/actions/typescript-action/pull/516

**Comment by ncalteen** [comment]
👋🏻 Hello! Apologies for the delay on this issue. I am going through this repository and making some large updates. This will be resolved by #732
