### ISSUE TITLE
ESLint config should extend from recommended configurations

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [actions/typescript-action#630]
[typescript-eslint provides recommended configurations that can be extended](https://typescript-eslint.io/linting/configs). Extending from them would enable some more useful rules -many of which are auto-fixable- and reduce the size of the ESLint config. Can we use them here?

Reference PR in a forked project: https://github.com/mtfoley/pr-compliance-action/pull/313

**Comment by ncalteen** [comment]
👋🏻 Hello! Apologies for the delay on this issue. I am going through this repository and making some large updates. This will be resolved by #732
