### ISSUE TITLE
This Template seems to be code rotting 😢 

### ISSUE THREAD

**Issue by JLLeitschuh** [actions/typescript-action#650]
Hey GitHub Actions Team,

This seems to be code-rotting. There are quite a few open PRs, especially from Dependabot, that have never been merged.

Of particular importance, the CodeQL action is not running the latest version. Additionally, running `npm install` from the repository flags one high severity vulnerability in `minimatch` (a vulnerability from 6 months ago) (https://github.com/advisories/GHSA-f8q6-p94x-37v3). Not a great look for a project that is supposed to be the base for all newly developed GitHub actions. Additionally, the latest NPM LTS is reported to not be supported (https://github.com/actions/typescript-action/issues/646).

**Comment by JLLeitschuh** [comment]
Using this template you are immediately greeted with the following pull requests from dependabot:

![Screenshot 2023-03-31 at 7 11 33 PM](https://user-images.githubusercontent.com/1323708/229248350-51116f9a-0969-4dc0-a040-1d07b92c5817.png)

**Comment by ncalteen** [comment]
Hello!

I just wanted to let you know we're working on some updates to this repository to resolve a number of issues. Specifically, we'll be working on the following to start:

- Update outdated dependencies (and close the Dependabot PRs)
- Resolve issues flagged by NPM and CodeQL
- Update to support Node.js 18.x

I will keep this issue open until the above are resolved, and then work through the other issues in this repo!
