### ISSUE TITLE
Run is called before first test

### ISSUE THREAD

**Issue by jmgilman** [actions/typescript-action#761]
I ran into an issue when creating a new action from this template. The sequence is roughly as follows:

1. The [`run` function](https://github.com/actions/typescript-action/blob/ed9cd5d03be933cb40d2e9c1c6e20ea3337a1a38/src/index.ts#L8) is executed [at the end of `index.ts`](https://github.com/actions/typescript-action/blob/main/src/index.ts#L29)
2. When the index is [imported](https://github.com/actions/typescript-action/blob/ed9cd5d03be933cb40d2e9c1c6e20ea3337a1a38/__tests__/index.test.ts#L10) in the test, the `run` function is inadvertently called. 
3. Despite the above, for whatever reason, [the mocks](https://github.com/actions/typescript-action/blob/main/__tests__/index.test.ts#L13) appear to take effect before `run` is actually called. 

The result is that the `run` function is actually called three times, however, the first time is outside of a test. You can validate this by simply adding a `console.log()` to the beginning of the `run` function and observe it appears 3 times in the log output after running the tests. 

As mentioned in step 2 above, there is no consequence to this in this example repository because ultimately everything is mocked by the time the first `run` execution takes place. However, there are cases where more advanced mocking is required in a test, and if that advanced mocking is not replicated at the top of the test file (such that the first execution of `run` is successful), then you'll start running into strange errors. 

The current workaround I have for this is to use two files:

1. A `run.ts` file which contains the actual `run` function
2. An `index.ts` file which simply imports and executes the `run` function

Then, in tests, I only import from `run.ts` to avoid the inadvertent call to the `run` function.

I am by no means a JS/TS expert, so I'm open to other workarounds. Either way, I would advise either documenting this drawback or potentially implementing a workaround to avoid consumers running into this in the future.

**Comment by ncalteen** [comment]
Hi @jmgilman, that's a good point, and one I had to work around when updating the tests. I agree it would simply be easier to have a wrapper that calls the action instead of invoking it directly in `index.ts`. I'll take a look at this one and make some updates.
