### ISSUE TITLE
"npm test" script eats failure-status (because "|| make-coverage-badge")

### ISSUE THREAD

**Issue by ebrannin-bw** [actions/typescript-action#799]
The `npm test` [script](https://github.com/actions/typescript-action/blob/main/package.json#L34-L35) eats failures, and breaks `&&` in `npm run all`:

```json
{
    "test": "(jest && make-coverage-badge --output-path ./badges/coverage.svg) || make-coverage-badge --output-path ./badges/coverage.svg",
    "all": "npm run format:write && npm run lint && npm run test && npm run package"
}
```

Because it runs `make-coverage-badge` on test failure, when I run `npm run all` it will run `npm run package` even if tests fail.

**Comment by ebrannin-bw** [comment]
This also breaks VS Code's Jest integration, because it expects to run `npm test -- --flag ...` and have the new arguments go to Jest.

**Comment by ncalteen** [comment]
Hey @ebrannin-bw, thanks for catching that! I've submitted #805 to fix this error using the workaround you provided :)
