### ISSUE TITLE
Add bun.lockb to .gitignore

### ISSUE THREAD

**Issue by kishaningithub** [actions/typescript-action#856]
## Context
- I am using [bun](https://bun.sh/) in my local development environment.
- I periodically sync the changes in this template to my github actions.

## Proposal
- Can `bun.lockb` be added to the `.gitignore` of this repo?

**Comment by kishaningithub** [comment]
May be this should be a separate request (let me know)

In the package.json i see that this codebase explicity puts `npx`, `npm` etc. It would be great if this can be made generic to support different runtimes like bun and deno for development purposes

**Comment by ncalteen** [comment]
Hi @kishaningithub, do you have a reference repository with this template configured to use Bun? It would be awesome to see how you have things set up and what could be done to make this repo more easily adopted by other JavaScript runtimes.

**Comment by ncalteen** [comment]
Closing this out for now due to lack of response. If you would like us to revisit please respond back with the requested info and we can investigate :)
