### ISSUE TITLE
I thought the proc were honoring subtyping of arrow types.

### ISSUE THREAD

**Issue by Ahmed30mara2018** [actions/typescript-action#884]
I thought the proc were honoring subtyping of arrow types.

It is safe for the following example to compile.

```cr
class Foo
end
 
class Bar < Foo
end
 
def foo(x : Proc(Bar, Nil))
  x
end
 
a = 1
 
proc = foo(->(b : Foo) { a = 2 })
r = proc.call(Bar.new)
```

It is subject for a later change, but is the subtying of arrow type in procs that we are missing it seems.

_Originally posted by @bcardiff in https://github.com/crystal-lang/crystal/pull/8969#discussion_r399835146_

**Comment by ncalteen** [comment]
Sorry I think this is the wrong repo for this question!
